jobs:
- job: BuildMacOS
  strategy:
    maxParallel: 10
    matrix:
      Node8:
        NODE_VERSION: '8.x'

  pool:
    vmImage: 'macOS-10.13'

  steps:
  - task: NodeTool@0
  displayName: 'Node Tool install $(NODE_VERSION)'
  inputs:
    versionSpec: '$(NODE_VERSION)'

  - script: npm install
    displayName: 'npm install'